---
title: "Introduction to R: Group Assignment"
author: "Jodi Tay Seow Xuan (8989982), Le Nguyen Ngoc Anh (2792915), Nil Avci (0889571)"
output: 
  html_document:
    toc: true
    number_sections: true
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
```

```{r}
library(dplyr)
library(tidyr)
library(tidyverse)
library(ggplot2)
library(gridExtra)
library(corrplot)
melb_housing <- read.csv("Melbourne_housing_FULL.csv")
```

# Introduction

# Cleaning

```{r include=FALSE}
# remove missing values from columns
melb_housing <- melb_housing[complete.cases(melb_housing$Price), ]
melb_housing <- melb_housing[complete.cases(melb_housing$YearBuilt), ]
melb_housing <- melb_housing[complete.cases(melb_housing$BuildingArea), ]

# drop columns of houses with Landsize = 0 
melb_housing <- subset(melb_housing, Landsize != 0)

# convert Distance to a numeric variable
melb_housing$Distance <- as.numeric(melb_housing$Distance)

# correlation plot 
mh_numeric <- melb_housing[, c("Price", "Rooms", "Distance", "Bedroom2", "Bathroom", "BuildingArea", "YearBuilt", "Landsize")]
corr_mat <- cor(mh_numeric)
corrplot(corr_mat, method = "number")
```

# Descriptive statistics

```{r}

# remove missing values from columns
melb_housing <- melb_housing[complete.cases(melb_housing$Price), ]
melb_housing <- melb_housing[complete.cases(melb_housing$YearBuilt), ]
melb_housing <- melb_housing[complete.cases(melb_housing$BuildingArea), ]

# drop columns of houses with Landsize = 0 
melb_housing <- subset(melb_housing, Landsize != 0)

# convert Distance to a numeric variable
melb_housing$Distance <- as.numeric(melb_housing$Distance)

# correlation plot 
mh_numeric <- melb_housing[, c("Price", "Rooms", "Distance", "Bedroom2", "Bathroom", "BuildingArea", "YearBuilt", "Landsize")]
corr_mat <- cor(mh_numeric)
corrplot(corr_mat, method = "number")
```

## Descriptive statistics

```{r}
ggplot(melb_housing, aes(x = Type, y = Price)) + 
  scale_y_continuous(labels = scales::comma) +
  geom_boxplot() +
  coord_flip()

melb_housing %>%
  group_by(Type) %>%
  summarise(mean(Price), sd(Price), median(Price))
```

```{r}
rooms_price <- ggplot(melb_housing, aes(x = Rooms, y = Price)) +
  scale_y_continuous(labels = scales::comma) +
  geom_point(alpha = 0.1) +
  geom_smooth(method = "lm", se = FALSE)

dist_price <- ggplot(melb_housing, aes(x = Distance, y = Price)) +
  scale_y_continuous(labels = scales::comma) +
  geom_point(alpha = 0.1) +
  geom_smooth(method = "lm", se = FALSE)

grid.arrange(rooms_price, dist_price)
```

# Linear regression

```{r}
#Multiple linear regression
lm_house <- lm(Price ~ Distance + Rooms + Type, melb_housing)
```

```{r}
#Assumptions of multiple linear regression
par(mfrow = c(2, 2))
plot(lm_house)
```

```{r}
#Summary of the regression
summary(lm_house) 
```

# Data visualisation

```{r echo=FALSE}
grid.arrange(
  ggplot(melb_housing, aes(Distance, Price, color = Type)) +
    geom_point() +
    geom_smooth(method = lm, se = F),
  ggplot(melb_housing, aes(Rooms, Price, color = Type)) +
    geom_point(position = "jitter") +
    geom_smooth(method = lm, se = F),
  nrow = 1
)
```
